spring:
  application:
    name: vector-db-demo
  ai:
    openai:
      api-key: ${OPENAI_API_KEY:}
    vectorstore:
      qdrant:
        initialize-schema: true
        host: localhost
        port: 6334
        collection-name: vector_db_demo_collection
  docker:
    compose:
      stop:
        command: down #  to stop and remove containers because qdrant needs fresh start in our demo case