spring:
  application:
    name: mcp-server-stdio
  main:
    web-application-type: none # non-web application, as this is a CLI application
    banner-mode: off # disable the Spring banner
  datasource:
    url: jdbc:h2:file:./chatmemory-h2db
    driver-class-name: org.h2.Driver
    username: SA
    password: SA
  h2:
    console:
      enabled: true
  jpa:
    hibernate:
      ddl-auto: update

logging:
  level:
    root: ERROR

