spring:
  application:
    name: openai
  ai:
    openai:
      api-key: ${OPENAI_API_KEY:}
    chat:
      memory:
        repository:
          jdbc:
            initialize-schema: always
            schema: classpath:/schema/chat_memory_schema-h2db.sql
  datasource:
    url: jdbc:h2:file:./chatmemory-h2db
    driver-class-name: org.h2.Driver
    username: SA
    password: SA

logging:
  pattern:
    console: "%green(%d{HH:mm:ss.SSS}) %blue(%-5level) %red([%thread]) %yellow(%logger{15}) - %msg%n"
  level:
    org.springframework.ai.chat.client.advisor: DEBUG

# configuring H2 Db for in-memory chat history storage


