spring:
  application:
    name: mcp-demo

  ai:
    openai:
      api-key: ${OPENAI_API_KEY:}
    mcp:
      client:
        stdio:
          servers-configuration: classpath:mcp-servers-configuration.json


logging:
  pattern:
    console: "%green(%d{HH:mm:ss.SSS}) %blue(%-5level) %red([%thread]) %yellow(%logger{15}) - %msg%n"
  level:
    org.springframework.ai.chat.client.advisor: DEBUG # required to see logs using SimpleLoggerAdvisor


