services:
  prometheus:
    image: prom/prometheus
    container_name: prometheus
    volumes:
      - "./prometheus-config.yml:/etc/prometheus/prometheus.yml"
    networks:
      - observability-demo # This value should be the application name defined in application.yaml (spring.application.name) to make sure that prometheus can access the application metrics endpoint.
    ports:
      - 9090:9090

# Define a custom network for the application because prometheus needs to access the application metrics endpoint.
# In a real-world scenario, you would likely have more complex network configurations and security considerations.
networks:
  observability-demo:
    driver: bridge #default network driver from docker