spring:
  application:
    name: multi-model-1
  ai:
    openai:
      api-key: ${OPENAI_API_KEY:}
    ollama:
      chat:
        options:
          model: llama3.2:1b
    chat:
      client:
        enabled: false # Disable default chat client
logging:
  pattern:
    console: "%green(%d{HH:mm:ss.SSS}) %blue(%-5level) %red([%thread]) %yellow(%logger{15}) - %msg%n"